/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mario.bancos.Ventanas.Paneles;

import com.mario.bancos.Clases.Usuario;
import com.mario.bancos.Clases.Hash;
import com.mario.bancos.Cliente;

import javax.swing.*;
import java.awt.*;
import java.security.NoSuchAlgorithmException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author MarioZatonToledo
 */
public class Panel_registro extends javax.swing.JPanel {

    /**
     * Creates new form Panel_registro
     */
    public Panel_registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        n_edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_pass = new javax.swing.JTextField();
        b_registro = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(622, 481));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Email:");

        jLabel6.setText("Usuario:");

        jLabel7.setText("Contraseña:");

        b_registro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_registro.setText("Registrarse");
        b_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    b_registroActionPerformed(evt);
                } catch (NoSuchAlgorithmException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_nombre)
                    .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(b_registro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(b_registro)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_registroActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException {//GEN-FIRST:event_b_registroActionPerformed

        int contErrores = 0;

        if(validarNombre(t_nombre.getText())==false){
            t_nombre.setText(t_nombre.getText()+"*");
            t_nombre.setForeground(Color.red);

            contErrores ++;
        }
        else {
            t_nombre.setForeground(Color.black);
        }

        if(validarApellido(t_apellido.getText())==false){
            t_apellido.setText(t_apellido.getText()+"*");
            t_apellido.setForeground(Color.red);

            contErrores ++;
        }

        if(validarEmail(t_email.getText())==false){
            t_email.setText(t_email.getText()+"*");
            t_email.setForeground(Color.red);

            contErrores ++;
        }

        if( validarContrasena(t_pass.getText())==false){
            t_pass.setText(t_pass.getText()+"*");
            t_pass.setForeground(Color.red);

            contErrores ++;
        }
        if( validarEdad(Integer.parseInt(n_edad.getValue().toString()))==false){
            t_pass.setText(t_pass.getText()+"*");
            t_pass.setForeground(Color.red);

            contErrores ++;
        }

        if(contErrores == 0){
            String pass = null;
            try{
                Hash md5 = new Hash();
                pass = Hash.hashear(t_pass.getText());

            }
            catch (Exception e){
                System.out.println("Error al hashear la contraseña: "+ e.getMessage());

            }

            String password = pass.toString();
            Usuario u = new Usuario(t_nombre.getText(), t_apellido.getText(), Integer.parseInt(n_edad.getValue().toString()),t_usuario.getText(),password,t_email.getText());
            u.setMetodo("registroUsuario");


            try{
                String[] buttons = { "Acepto"};
                int returnValue = JOptionPane.showOptionDialog(null, "A continuacion deberás firmar el acuerdo de uso del banco para crear una cuenta", "Acepto Banco",
                        JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[0]);

                if(returnValue == 0)
                    u.setFirmaDigital("acepto");

                Cliente.insertarCliente(u);
                JOptionPane.showMessageDialog(null, "El alumno ha sido añadido con exito");

            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error en la inserción del usuario");
            }
        }
    }//GEN-LAST:event_b_registroActionPerformed


    private boolean validarNombre(String nombre) {

        Pattern pnombre= Pattern.compile("^[A-Z][a-z]+$");
        Matcher mnombre= pnombre.matcher(nombre);

        if(mnombre.matches()){
            return true;
        }
        else
            return false;

    }
    private boolean validarApellido(String apellido) {
        Pattern papellido = Pattern.compile("^[A-Z][a-z]+$");
        Matcher mapellido= papellido.matcher(apellido);
        
        if(mapellido.matches()){
            return true;
        }
        else{
            return false;
        }
    }

    private boolean validarContrasena(String apellido) {
        Pattern pPass = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,12}$");
        Matcher mPass= pPass.matcher(apellido);

        if(mPass.matches()){
            return true;
        }
        else{
            return false;
        }
    }


    private boolean validarEmail(String email) {
        Pattern pEmail= Pattern.compile("^[A-z0-9,._-]+@(ikasle.egibide.org|gmail.com)$");
        Matcher mEmail = pEmail.matcher(email);
        if(mEmail.matches())
            return true;
        else 
            return false;
    }

    private boolean validarEdad(int edad) {

        if(edad < 18)
            return false;
        else
            return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner n_edad;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_usuario;
    // End of variables declaration//GEN-END:variables
}
