/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mario.bancos.Ventanas.Paneles;

import com.mario.bancos.Cliente;

/**
 *
 * @author mario
 */
public class Panel_ingresoRetiro extends javax.swing.JPanel {

    /**
     * Creates new form Panel_ingresoRetiro
     */
    public Panel_ingresoRetiro() {
        initComponents();
        rb_group.add(rb_ingreso);
        rb_group.add(rb_retiro);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        n_cantidad = new javax.swing.JSpinner();
        rb_ingreso = new javax.swing.JRadioButton();
        rb_retiro = new javax.swing.JRadioButton();
        b_movimiento = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Retirar / Ingresar");

        n_cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                n_cantidadStateChanged(evt);
            }
        });

        rb_ingreso.setSelected(true);
        rb_ingreso.setText("Ingreso");

        rb_retiro.setText("Retiro");

        b_movimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_movimiento.setText("Efectuar movimiento");
        b_movimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_movimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(rb_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(rb_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_movimiento)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(342, 342, 342))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(n_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_ingreso)
                    .addComponent(rb_retiro))
                .addGap(52, 52, 52)
                .addComponent(b_movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_movimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_movimientoActionPerformed
        String movimiento;
        if (rb_ingreso.isSelected()){
             movimiento = "ingreso";
        }
        else{
            movimiento = "retiro";
        }
        int cantidad = Integer.parseInt(n_cantidad.getValue().toString());

        if(cantidad > 0 && cantidad<= 500) {
            
            //Cliente.crearMovimiento();
        }
    }//GEN-LAST:event_b_movimientoActionPerformed

    private void n_cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_n_cantidadStateChanged
        // TODO add your handling code here:
        if(Integer.parseInt(n_cantidad.getValue().toString())> 500){
            n_cantidad.setValue(500);
        }

    }//GEN-LAST:event_n_cantidadStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_movimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner n_cantidad;
    private javax.swing.ButtonGroup rb_group;
    private javax.swing.JRadioButton rb_ingreso;
    private javax.swing.JRadioButton rb_retiro;
    // End of variables declaration//GEN-END:variables
}
